"""initial schema

Revision ID: da9ab5998e36
Revises: 
Create Date: 2026-05-22 18:15:35.117758
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'da9ab5998e36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_strategy_name'), ['strategy_name'], unique=False)

    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_actions_action_date'), ['action_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_actions_symbol'), ['symbol'], unique=False)

    op.create_table('daily_ohlcv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('turnover_value', sa.Float(), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'symbol', 'venue', name='uq_daily_symbol_date_venue')
    )
    with op.batch_alter_table('daily_ohlcv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_ohlcv_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_ohlcv_trade_date'), ['trade_date'], unique=False)

    op.create_table('data_quality_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('check_code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_checks_check_code'), ['check_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_checks_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_checks_severity'), ['severity'], unique=False)

    op.create_table('data_sources',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('provider_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('zero_volume_policy', sa.String(length=64), nullable=False),
    sa.Column('unknown_symbol_policy', sa.String(length=64), nullable=False),
    sa.Column('max_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_provider_type'), ['provider_type'], unique=False)

    op.create_table('external_symbol_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('external_symbol', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_symbol', name='uq_external_symbol_source')
    )
    with op.batch_alter_table('external_symbol_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_symbol_mapping_external_symbol'), ['external_symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_symbol_mapping_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_symbol_mapping_symbol'), ['symbol'], unique=False)

    op.create_table('fundamentals_pti',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asof_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('eps', sa.Float(), nullable=False),
    sa.Column('op_margin', sa.Float(), nullable=False),
    sa.Column('roe', sa.Float(), nullable=False),
    sa.Column('gross_profitability', sa.Float(), nullable=False),
    sa.Column('quarterly_eps_growth', sa.Float(), nullable=False),
    sa.Column('sales_growth', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'asof_date', 'effective_date', name='uq_fund_symbol_asof_effective')
    )
    with op.batch_alter_table('fundamentals_pti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fundamentals_pti_asof_date'), ['asof_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamentals_pti_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamentals_pti_symbol'), ['symbol'], unique=False)

    op.create_table('import_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('provider_type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('can_confirm', sa.Boolean(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('info_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('staged_rows_json', sa.Text(), nullable=False),
    sa.Column('preview_rows_json', sa.Text(), nullable=False),
    sa.Column('source_config_snapshot_json', sa.Text(), nullable=False),
    sa.Column('provider_metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_runs_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_runs_provider_type'), ['provider_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_runs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_runs_status'), ['status'], unique=False)

    op.create_table('index_ohlcv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'symbol', name='uq_index_symbol_date')
    )
    with op.batch_alter_table('index_ohlcv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_index_ohlcv_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_index_ohlcv_trade_date'), ['trade_date'], unique=False)

    op.create_table('indicator_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('turnover_value', sa.Float(), nullable=False),
    sa.Column('sma20', sa.Float(), nullable=True),
    sa.Column('sma50', sa.Float(), nullable=True),
    sa.Column('sma150', sa.Float(), nullable=True),
    sa.Column('sma200', sa.Float(), nullable=True),
    sa.Column('sma200_slope', sa.Float(), nullable=True),
    sa.Column('volume_ma20', sa.Float(), nullable=True),
    sa.Column('volume_ma50', sa.Float(), nullable=True),
    sa.Column('atr14', sa.Float(), nullable=True),
    sa.Column('atr20', sa.Float(), nullable=True),
    sa.Column('atr20_pct', sa.Float(), nullable=True),
    sa.Column('atr20_pct_ma60', sa.Float(), nullable=True),
    sa.Column('std20', sa.Float(), nullable=True),
    sa.Column('std60', sa.Float(), nullable=True),
    sa.Column('high_52w', sa.Float(), nullable=True),
    sa.Column('distance_from_52w_high', sa.Float(), nullable=True),
    sa.Column('volume_ratio_50', sa.Float(), nullable=True),
    sa.Column('pivot_high_20_prev', sa.Float(), nullable=True),
    sa.Column('pivot_low_20_prev', sa.Float(), nullable=True),
    sa.Column('breakout', sa.Boolean(), nullable=False),
    sa.Column('volume_dry_up', sa.Boolean(), nullable=False),
    sa.Column('rs_percentile', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('volume_score', sa.Float(), nullable=False),
    sa.Column('pattern_score', sa.Float(), nullable=False),
    sa.Column('fund_score', sa.Float(), nullable=False),
    sa.Column('market_score', sa.Float(), nullable=False),
    sa.Column('sector_rs_score', sa.Float(), nullable=False),
    sa.Column('relative_strength_score', sa.Float(), nullable=False),
    sa.Column('rr_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'symbol', name='uq_indicator_symbol_date')
    )
    with op.batch_alter_table('indicator_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicator_snapshot_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicator_snapshot_trade_date'), ['trade_date'], unique=False)

    op.create_table('orders',
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)

    op.create_table('paper_audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('paper_order_id', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason_codes_json', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_audit_events_event_type'), ['event_type'], unique=False)

    op.create_table('paper_fills',
    sa.Column('paper_fill_id', sa.String(length=64), nullable=False),
    sa.Column('paper_order_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fill_ts', sa.DateTime(), nullable=False),
    sa.Column('fill_source', sa.String(length=32), nullable=False),
    sa.Column('simulator_version', sa.String(length=32), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('slippage_bps', sa.Float(), nullable=False),
    sa.Column('live_order_created', sa.Boolean(), nullable=False),
    sa.Column('broker_order_created', sa.Boolean(), nullable=False),
    sa.Column('network_call_performed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('paper_fill_id')
    )
    with op.batch_alter_table('paper_fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_fills_paper_order_id'), ['paper_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_fills_symbol'), ['symbol'], unique=False)

    op.create_table('paper_orders',
    sa.Column('paper_order_id', sa.String(length=64), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('strategy_tag', sa.String(length=64), nullable=True),
    sa.Column('reason_codes_json', sa.Text(), nullable=False),
    sa.Column('risk_gate_json', sa.Text(), nullable=False),
    sa.Column('live_order_created', sa.Boolean(), nullable=False),
    sa.Column('broker_order_created', sa.Boolean(), nullable=False),
    sa.Column('network_call_performed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('paper_order_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_orders_symbol'), ['symbol'], unique=False)

    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('strategy_tag', sa.String(length=64), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_positions_symbol'), ['symbol'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('entry_ts', sa.DateTime(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('strategy_tag', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)

    op.create_table('reports',
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_report_date'), ['report_date'], unique=False)

    op.create_table('screen_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('strategy_tag', sa.String(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('pass_flags', sa.Text(), nullable=False),
    sa.Column('failed_conditions', sa.Text(), nullable=False),
    sa.Column('reason_summary', sa.Text(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('risk_per_share', sa.Float(), nullable=True),
    sa.Column('reward_risk_ratio', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Integer(), nullable=False),
    sa.Column('position_notional', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_results_strategy_tag'), ['strategy_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_results_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_results_trade_date'), ['trade_date'], unique=False)

    op.create_table('sector_ohlcv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'sector', name='uq_sector_date')
    )
    with op.batch_alter_table('sector_ohlcv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sector_ohlcv_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_sector_ohlcv_trade_date'), ['trade_date'], unique=False)

    op.create_table('symbol_master',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('delist_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('trading_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'calendar_date', name='uq_trading_calendar_market_date')
    )
    with op.batch_alter_table('trading_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_calendar_calendar_date'), ['calendar_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_calendar_market'), ['market'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_calendar_market'))
        batch_op.drop_index(batch_op.f('ix_trading_calendar_calendar_date'))

    op.drop_table('trading_calendar')
    op.drop_table('symbol_master')
    with op.batch_alter_table('sector_ohlcv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_ohlcv_trade_date'))
        batch_op.drop_index(batch_op.f('ix_sector_ohlcv_sector'))

    op.drop_table('sector_ohlcv')
    with op.batch_alter_table('screen_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_results_trade_date'))
        batch_op.drop_index(batch_op.f('ix_screen_results_symbol'))
        batch_op.drop_index(batch_op.f('ix_screen_results_strategy_tag'))

    op.drop_table('screen_results')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_report_date'))

    op.drop_table('reports')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))

    op.drop_table('positions')
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_positions_symbol'))

    op.drop_table('paper_positions')
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_orders_symbol'))

    op.drop_table('paper_orders')
    with op.batch_alter_table('paper_fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_fills_symbol'))
        batch_op.drop_index(batch_op.f('ix_paper_fills_paper_order_id'))

    op.drop_table('paper_fills')
    with op.batch_alter_table('paper_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_audit_events_event_type'))

    op.drop_table('paper_audit_events')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))

    op.drop_table('orders')
    with op.batch_alter_table('indicator_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicator_snapshot_trade_date'))
        batch_op.drop_index(batch_op.f('ix_indicator_snapshot_symbol'))

    op.drop_table('indicator_snapshot')
    with op.batch_alter_table('index_ohlcv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_index_ohlcv_trade_date'))
        batch_op.drop_index(batch_op.f('ix_index_ohlcv_symbol'))

    op.drop_table('index_ohlcv')
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_runs_status'))
        batch_op.drop_index(batch_op.f('ix_import_runs_source_id'))
        batch_op.drop_index(batch_op.f('ix_import_runs_provider_type'))
        batch_op.drop_index(batch_op.f('ix_import_runs_file_hash'))

    op.drop_table('import_runs')
    with op.batch_alter_table('fundamentals_pti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fundamentals_pti_symbol'))
        batch_op.drop_index(batch_op.f('ix_fundamentals_pti_effective_date'))
        batch_op.drop_index(batch_op.f('ix_fundamentals_pti_asof_date'))

    op.drop_table('fundamentals_pti')
    with op.batch_alter_table('external_symbol_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_symbol_mapping_symbol'))
        batch_op.drop_index(batch_op.f('ix_external_symbol_mapping_source_id'))
        batch_op.drop_index(batch_op.f('ix_external_symbol_mapping_external_symbol'))

    op.drop_table('external_symbol_mapping')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_provider_type'))

    op.drop_table('data_sources')
    with op.batch_alter_table('data_quality_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_checks_severity'))
        batch_op.drop_index(batch_op.f('ix_data_quality_checks_run_id'))
        batch_op.drop_index(batch_op.f('ix_data_quality_checks_check_code'))

    op.drop_table('data_quality_checks')
    with op.batch_alter_table('daily_ohlcv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_ohlcv_trade_date'))
        batch_op.drop_index(batch_op.f('ix_daily_ohlcv_symbol'))

    op.drop_table('daily_ohlcv')
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_actions_symbol'))
        batch_op.drop_index(batch_op.f('ix_corporate_actions_action_type'))
        batch_op.drop_index(batch_op.f('ix_corporate_actions_action_date'))

    op.drop_table('corporate_actions')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_strategy_name'))

    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
